[package]
name = "day_1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0.0", features = ["full"] }

[dev-dependencies]
cucumber = "0.20.1"

[[test]]
name = "day_1"
harness = false
